src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use function PHPUnit\Framework\isEmpty;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $affiche = null;

    #[ORM\Column]
    private ?float $tarifLibre = null;

    #[ORM\Column]
    private ?float $tarifMembre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $datePublication = null;

    #[ORM\Column(length: 300)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $lienInscription = "";

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateLimiteInscription = null;

    #[ORM\Column]
    private ?int $placesRestantes = null;

    #[ORM\Column(length: 255)]
    private ?string $afficheFerme = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?LieuEvenement $aLieuA = null;

    #[ORM\ManyToMany(targetEntity: Entreprise::class, mappedBy: 'entrepriseEvenement')]
    private Collection $entreprisesParticipantes;

    public function __construct()
    {
        $this->entreprisesParticipantes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): static
    {
        $this->affiche = $affiche;

        return $this;
    }

    public function getTarifLibre(): ?float
    {
        return $this->tarifLibre;
    }

    public function setTarifLibre(float $tarifLibre): static
    {
        $this->tarifLibre = $tarifLibre;

        return $this;
    }

    public function getTarifMembre(): ?float
    {
        return $this->tarifMembre;
    }

    public function setTarifMembre(float $tarifMembre): static
    {
        $this->tarifMembre = $tarifMembre;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->datePublication;
    }

    public function setDatePublication(\DateTimeInterface $datePublication): static
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLienInscription(): ?string
    {
        return $this->lienInscription;
    }

    public function setLienInscription(string $lienInscription): static
    {
        $this->lienInscription = $lienInscription;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->dateLimiteInscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $dateLimiteInscription): static
    {
        $this->dateLimiteInscription = $dateLimiteInscription;

        return $this;
    }

    public function getPlacesRestantes(): ?int
    {
        return $this->placesRestantes;
    }

    public function setPlacesRestantes(int $placesRestantes): static
    {
        $this->placesRestantes = $placesRestantes;

        return $this;
    }

    public function getAfficheFerme(): ?string
    {
        return $this->afficheFerme;
    }

    public function setAfficheFerme(string $afficheFerme): static
    {
        $this->afficheFerme = $afficheFerme;

        return $this;
    }

    public function getALieuA(): ?lieuEvenement
    {
        return $this->aLieuA;
    }

    public function setALieuA(lieuEvenement $aLieuA): static
    {
        $this->aLieuA = $aLieuA;

        return $this;
    }

    /**
     * @return Collection<int, Entreprise>
     */
    public function getEntreprisesParticipantes(): Collection
    {
        return $this->entreprisesParticipantes;
    }

    public function addEntreprisesParticipante(Entreprise $entreprisesParticipante): static
    {
        if (!$this->entreprisesParticipantes->contains($entreprisesParticipante)) {
            $this->entreprisesParticipantes->add($entreprisesParticipante);
            $entreprisesParticipante->addEntrepriseEvenement($this);
        }

        return $this;
    }

    public function removeEntreprisesParticipante(Entreprise $entreprisesParticipante): static
    {
        if ($this->entreprisesParticipantes->removeElement($entreprisesParticipante)) {
            $entreprisesParticipante->removeEntrepriseEvenement($this);
        }

        return $this;
    }

    public function getDateString(): string {
        return $this->date->format("d/m/Y");
    }

    public function getDatePublicationString(): string {
        return $this->date->format("d/m/Y");
    }

    public function getDateLimiteInscriptionString(): string {
        return $this->date->format("d/m/Y");
    }

    public function getIsLien(): bool {
        return !isEmpty($this->lienInscription);
    }

    public function getNbEntreprises(): bool {
        return sizeof($this->getEntreprisesParticipantes());
    }

}

src/Entity/OffreEmploi.php
<?php

namespace App\Entity;

use App\Repository\OffreEmploiRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreEmploiRepository::class)]
class OffreEmploi
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nomPoste = null;

    #[ORM\Column(length: 300)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'offreEmplois')]
    #[ORM\JoinColumn(nullable: false)]
    private ?NiveauDetude $pourNiveauDetude = null;

    #[ORM\ManyToOne(inversedBy: 'offreEmplois')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $parEntreprise = null;

    #[ORM\Column(length: 255)]
    #[ORM\JoinColumn(nullable: false)]
    private ?string $mailContact = null;

    #[ORM\Column]
    private ?bool $isRemunere = null;

    #[ORM\Column(length: 10)]
    private ?string $telContact = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNomPoste(): ?string
    {
        return $this->nomPoste;
    }

    public function setNomPoste(string $nomPoste): static
    {
        $this->nomPoste = $nomPoste;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPourNiveauDetude(): ?NiveauDetude
    {
        return $this->pourNiveauDetude;
    }

    public function setPourNiveauDetude(?NiveauDetude $pourNiveauDetude): static
    {
        $this->pourNiveauDetude = $pourNiveauDetude;

        return $this;
    }

    public function getParEntreprise(): ?Entreprise
    {
        return $this->parEntreprise;
    }

    public function setParEntreprise(?Entreprise $parEntreprise): static
    {
        $this->parEntreprise = $parEntreprise;

        return $this;
    }

    public function getMailContact(): ?string
    {
        return $this->mailContact;
    }

    public function setMailContact(string $mailContact): static
    {
        $this->mailContact = $mailContact;

        return $this;
    }

    public function getDureeStage(): ?string
    {
        $debut = $this->pourNiveauDetude->getDebutStage();
        $fin = $this->pourNiveauDetude->getFinStage();
        return $debut->diff($fin)->format("%m mois et %d jours");
    }

    public function getTypePrestation(): ?string
    {
        return ucfirst($this->getPourNiveauDetude()->getTypePrestation()->getLibelle());
    }

    public function isIsRemunere(): ?bool
    {
        return $this->isRemunere;
    }

    public function setIsRemunere(bool $isRemunere): static
    {
        $this->isRemunere = $isRemunere;

        return $this;
    }

    public function getTelContact(): ?string
    {
        return $this->telContact;
    }

    public function setTelContact(string $telContact): static
    {
        $this->telContact = $telContact;

        return $this;
    }
}

templates/guest/amigo.html.twig
{% extends 'base.html.twig' %}

{% block title %}A propos de l'AMIGO{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="text-center">{{ textes['amigoDescTitre'] }}</h1>
            <p class="text-justify">{{ textes['amigoDesc'] }}</p>
            <h2 class="text-center">{{ textes['amigoMembresTitre'] }}</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8" id="carousel-container">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% set first = true %}
                    {% for membre in membres %}
                        {% if first %}
                            <div class="carousel-item active">
                            {% set first = false %}
                        {% else %}
                            <div class="carousel-item">
                        {% endif %}
                            <img src="{{ asset( membre.photo ) }}" class="d-block rounded-circle mx-auto" alt="Profile 1">
                            <div class="info">
                                <h3>{{ membre.prenom}} {{ membre.nom}}</h3>
                                <p class="paragraphe">{{ membre.description}}</p>
                                <p><a href="mailto:{{ membre.mail }}">{{ membre.mail }}</a></p>
                                <!-- <p>{{ membre.niveau }}</p> -->
                            </div>
                        </div>

                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon text-dark" aria-hidden="true"><</span>
                    <span class="sr-only">Précédent</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon text-dark" aria-hidden="true">></span>
                    <span class="sr-only">Suivant</span>
                </a>
            </div>
        </div>
    </div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}

templates/guest/entreprises.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block stylesheets %}
    <link href="/css/entreprises.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block body %}
    <h1 class="page-title">{{ textes[titre] }}</h1>
    <div class="search-container">
        {% if titre=="entrepriseTitre" %}
            <a href="{{ path('entreprisesMXE') }}" class="search-button">Voir uniquement Miage X Entreprises</a>
        {% else %}
            <a href="{{ path('entreprises') }}" class="search-button">Voir toutes les entreprises</a>
        {% endif %}
    </div>
    {% set compteur = 0 %}
    {% for entreprise in entreprises %}
        <div class="container-entreprise">
            <div class="entreprise-card">
                <div class="image-container">
                    <img src="{{ entreprise.logo }}" alt="{{ entreprise.nom }}">
                </div>
                <div class="info-container">
                    <div class="textes">
                        <h2>{{ entreprise.nom }}</h2>
                        <div class="tags">
                            {% for tag in entreprise.tagsEntreprise %}
                                <div class="tag"><span class="dot" style="background-color: #{{ tag.couleur }}"></span>{{ tag.libelle }}</div>
                            {% endfor %}
                        </div>
                        <div class="social-links">
                            <a target="_blank" href="{{ entreprise.site }}">Visiter leur site</a>
                            <a target="_blank" href="{{ entreprise.linkedIn }}"><img
                                        src="{{ asset("/images/assets/logoLinkedIn.png") }}"
                                        alt="LinkedIn"
                                        style="width: 20px;">
                            </a>
                        </div>
                        <p class="afficherplus text-justify" id="details{{ compteur }}">{{ entreprise.description }}</p>
                    </div>
                    <!-- Bouton collapsible -->
                    <div class="collapsible" id="fleche{{ compteur }}" onclick="toggleVisibility('details{{ compteur }}', 'fleche{{ compteur }}')">↓</div>
                </div>
            </div>
        </div>
        {% set compteur = compteur + 1 %}
    {% endfor %}
    <!-- Script pour le collapsible -->
    <script>
        function toggleVisibility(truc1, truc2) {
            let div1 = document.getElementById(truc1);
            let div2 = document.getElementById(truc2);
            if(div1.style.display === "block") {
                div1.style.display = "none";
                div2.innerHTML = "↓"
            } else {
                div1.style.display = "block";
                div2.innerHTML = "↑"
            }
        }
    </script>


{% endblock %}

templates/guest/evenements.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% endblock %}
{% block stylesheets %}
    <link href="/css/evenement.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block body %}
    <h1 class="text-center">Evenements à venir</h1>
    <div class="gros-evenements">
        {% for paire in upcoming %}
                <div class="conteneur-gros-evenements">
            {% for event in paire %}
                <div class="gros-evenement">
                    <div class="moitie">
                        <img src="{{ event.affiche }}" alt="Affiche pour {{ event.nom }}">
                    </div>
                    <div class="moitie">
                        <h1>{{ event.nom}}</h1>
                        <p><span>Date de l'évènement: {{ event.dateString }}</span></p>
                        <p><span class="petit-titre">Emplacement de l'évènement:</span> <br/>{{ event.aLieuA.nom }}<br/><span class="petit-texte">{{ event.aLieuA.adresse }}</span></p>
                        {% if(event.isLien) %}
                            <a href="{{ event.lienInscription }}">Inscription</a>
                        {% endif %}
                        <br>
                        {% if event.nbEntreprises != 0 %}
                            <p><span>Entreprises participantes : </span></p>
                            <div class="tags">
                                {% for entreprise in event.entreprisesParticipantes %}
                                        <div class="tag">
                                            <span class="dot" style="background-image: url('{{ entreprise.logo }}');"></span>{{ entreprise.nom }}
                                        </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div><!-- public/css/evenement.css -->
    <h2 class="" style="color: var(--primary)">Evenements passés</h2>
    <hr class="separateur" style="width: 30%">
        {% set compteur = 0 %}
        {% for annee in past %}
        <div class="liste-passes"> <!-- ⌃ -->
            <div class="lien-div" onclick="developper({{ compteur }}, {{ annees[compteur] }})"><h2 id="fleche{{ compteur }}"><i class="fa-solid fa-angle-up">{{ annees[compteur] }}</i></h2></div>
            <div class="liste-event" id="liste{{ compteur }}">
                {% for event in annee %}
                    <div class="carte-event">
                        <img src="{{ event.affiche }}">
                        <h4><a href="{{ path("evenementDetails") }}?evenmenet={{ event.nom }}">{{ event.nom }}</a></h4>
                        <p>{{ event.dateString }}</p>
                    </div>
                {% endfor %}
            </div>
            {% set compteur = compteur + 1 %}
        </div>
        {% endfor %}
    </div>

    <script>
        let collapsed = true;
        function developper(id, annee) {
            let div2 = document.getElementById("fleche"+id);
            let div1 = document.getElementById("liste"+id);
            if(collapsed) {
                collapsed = false;
                div1.style.display = "flex";
                div2.innerHTML = '<i class="fa-solid fa-angle-down">'+annee+'</i>';
            } else {
                collapsed = true;
                div1.style.display = "none";
                div2.innerHTML = '<i class="fa-solid fa-angle-up">'+annee+'</i>';
            }
        }
    </script>
{% endblock %}

templates/guest/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AMIGO{% endblock %}

{% block body %}
<script>

</script>
<div class="test">
    <div class="divbody">
        <div class="container">
            <div class="carteinfo">
                <h1>{{ textes['miageDescTitre'] }}</h1>
                <p class="textecentre">{{ textes['miageDesc'] }}</p>
                <ul class="textecentre">
                    <li>{{ textes['miageLi1'] }}</li>
                    <li>{{ textes['miageLi2'] }}</li>
                    <li>{{ textes['miageLi3'] }}</li>
                    <li>{{ textes['miageLi4'] }}</li>
                    <li>{{ textes['miageLi5'] }}</li>
                </ul>
            </div>
            <hr class="separateur">
            <h2>{{ textes['speTitre'] }}</h2>
            <div class="d-flex justify-content-between mt-3 align-self-stretch conteneur-cards">
                <div class="card">
                    <div class="card-details">
                        <p class="text-title">{{ textes['spe1Titre'] }}</p>
                        <p class="text-body"><span class="text-muted">{{ textes['spe1TitreLong'] }}</span></p>
                        <p>{{ textes['spe1Desc'] }}</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-details">
                        <p class="text-title">{{ textes['spe2Titre'] }}</p>
                        <p class="text-body"><span class="text-muted">{{ textes['spe2TitreLong'] }}</span></p>
                        <p>{{ textes['spe2Desc'] }}</p>
                    </div>
                </div>
            </div>

            <div class="carteinfo">
                <h2>{{ textes['contactTitre'] }}</h2>
                <p class="textecentre horaires">{{ textes['contactHoraires'] }}</p>
                <div class="container">
                    <!-- Horaires -->
                    <div class="row mt-4">
                        <div class="col-md-12 text-center">
                            <h4>{{ textes['contactMiageTitre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactMiageMail'] }}">{{ textes['contactMiageMail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}+33 456 789 123</p>
                        </div>
                    </div>
                    <!-- Informations de contact pour le professeur responsable -->
                    <div class="row mt-4 d-flex justify-content-between">

                        <div class="col-md-4">
                            <h4>{{ textes['contactL3Titre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactL3Mail'] }}">{{ textes['contactL3Mail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}{{ textes['contactL3Tel'] }}</p>
                        </div>
                        <div class="col-md-4">
                            <h4>{{ textes['contactM1Titre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactM1Mail'] }}">{{ textes['contactM1Mail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}{{ textes['contactM1Tel'] }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/guest/miage.html.twig
{% extends 'base.html.twig' %}

{% block title %}AMIGO{% endblock %}

{% block body %}
<script>

</script>
<div class="test">
    <div class="divbody">
        <div class="container">
            <div class="carteinfo">
                <h1>{{ textes['miageDescTitre'] }}</h1>
                <p class="textecentre">{{ textes['miageDesc'] }}</p>
                <ul class="textecentre">
                    <li>{{ textes['miageLi1'] }}</li>
                    <li>{{ textes['miageLi2'] }}</li>
                    <li>{{ textes['miageLi3'] }}</li>
                    <li>{{ textes['miageLi4'] }}</li>
                    <li>{{ textes['miageLi5'] }}</li>
                </ul>
            </div>
            <hr class="separateur">
            <h2 class="text-center">{{ textes['speTitre'] }}</h2>
            <div class="d-flex justify-content-between mt-3 align-self-stretch conteneur-cards">
                <div class="card">
                    <div class="card-details">
                        <p class="text-title">{{ textes['spe1Titre'] }}</p>
                        <p class="text-body"><span class="text-muted">{{ textes['spe1TitreLong'] }}</span></p>
                        <p class="text-justify">{{ textes['spe1Desc'] }}</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-details">
                        <p class="text-title">{{ textes['spe2Titre'] }}</p>
                        <p class="text-body"><span class="text-muted">{{ textes['spe2TitreLong'] }}</span></p>
                        <p class="text-justify">{{ textes['spe2Desc'] }}</p>
                    </div>
                </div>
            </div>

            <hr class="separateur">
            <br/>
            <div class="carteinfo">
                <h2>{{ textes['contactTitre'] }}</h2>
                <p class="textecentre horaires">{{ textes['contactHoraires'] }}</p>
                <div class="container">
                    <!-- Horaires -->
                    <div class="row mt-4">
                        <div class="col-md-12 text-center">
                            <h4>{{ textes['contactMiageTitre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactMiageMail'] }}">{{ textes['contactMiageMail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}+33 456 789 123</p>
                        </div>
                    </div>
                    <!-- Informations de contact pour le professeur responsable -->
                    <div class="row mt-4 d-flex justify-content-between">

                        <div class="col-md-4">
                            <h4>{{ textes['contactL3Titre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactL3Mail'] }}">{{ textes['contactL3Mail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}{{ textes['contactL3Tel'] }}</p>
                        </div>
                        <div class="col-md-4">
                            <h4>{{ textes['contactM1Titre'] }}</h4>
                            <p>{{ textes['contactMail'] }}<a href="{{ textes['contactM1Mail'] }}">{{ textes['contactM1Mail'] }}</a></p>
                            <p>{{ textes['contactTel'] }}{{ textes['contactM1Tel'] }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/guest/offres_stages_alternances.html.twig
{% extends 'base.html.twig' %}

{% block title %}OFFRES ET ALTERNANCES{% endblock %}
{% block stylesheets %}
    <link href="/css/offres.css" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block body %}






    <div class="test">
        <div class="divbody">
            <div class="container">
                <h1 class="">Offres de stages</h1>
                <hr class="style14">

                <!-- Les boutons permettants de choisir le niveau d'étude -->
                <div class="col-md-12 text-center">
                    <div class="btn-group btn-group-toggle block-bouton" data-toggle="buttons">
                        {% set oui = true %}
                        <a href="?niveau=L3+MIAGE">
                            <label class="btn btn-secondary {% if niveau=="L3 MIAGE" %}{% set oui = false %}active{% endif %}">
                            L3
                            </label>
                        </a>
                        <a href="?niveau=M1+MIAGE">
                            <label class="btn btn-secondary {% if niveau=="M1 MIAGE" %}{% set oui = false %}active{% endif %}">
                                M1
                            </label>
                        </a>
                        <a href="?niveau=M2+MIAGE">
                            <label class="btn btn-secondary {% if niveau=="M2 MIAGE" %}{% set oui = false %}active{% endif %}">
                                M2
                            </label>
                        </a>
                        <a href="?niveau=tous">
                            <label class="btn btn-secondary {% if oui %}active{% endif %}">
                                X
                            </label>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>





    <div class="container-cartes">
    {% for offre in offres %}
        <div class="image-container">
            <img src="{{ offre.parEntreprise.logo }}" alt="Votre image">
            <div class="typePrestation">{{ offre.typePrestation }}</div>
            <div class="info">
                <h2 class="title">{{ offre.nomPoste }}</h2>
                <h5>{{ offre.parEntreprise.nom }}</h5>
                <p class="description">{{ offre.description }}</p>
                <hr>
                <div class="details">
                    <p><span>Durée du stage : </span>{{ offre.dureeStage }}</p>
                    <p><span>Prestation : </span>{{ offre.typePrestation }}</p>
                    <p><span>Gratifications : </span> {% if offre.isRemunere %}Rémunéré{% else %}Non-Rémunéré{% endif %}</p>
                </div>
                <h3>Contactez-nous</h3>
                <div class="icons">
                    <a href="mailto:{{ offre.mailContact }}"><img
                                src="https://png.pngtree.com/png-vector/20190927/ourmid/pngtree-email-icon-png-image_1757854.jpg"
                                alt="Mail"></a>
                    <a target="_blank" href="{{ offre.parEntreprise.linkedIn }}"><img
                                src="https://toppng.com/uploads/preview/linkedin-logo-black-png-linkedin-icon-black-and-white-11562906557v2906x3pr2.png"
                                alt="LinkedIn"></a>
                    <a href="#"><img
                                src="https://www.kindpng.com/picc/m/346-3461748_telephone-logo-png-telephone-icon-png-transparent-png.png"
                                alt="Téléphone"></a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>















    </div>
    </div>
    </div>

{% endblock %}

templates/guest/tempo.html.twig
<style>
    .container {
        position: relative;
        width: 30%;
        height: 400px; /* Hauteur de la section */
        background-image: url('{{ asset('images/logoEntreprise/sopra.png') }}');
        background-size: cover;
        background-position: center;
        overflow: hidden; /* Pour cacher le débordement de l'image */
        border-radius: 10px; /* Coins arrondis */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); /* Ombre légère sur tous les côtés */
        transition: box-shadow 0.3s; /* Transition pour l'effet de survol */
    }

    .container:hover {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.5); /* Ombre légèrement plus prononcée au survol */
    }

    .content {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) translateY(30px);
        text-align: center;
        color: #000; /* Couleur du texte */
        transition: 1s ease-out; /* Transition pour l'effet de survol */
        opacity: 0; /* Par défaut, le contenu est caché */
        border-radius: 15px;
        padding: 5px;
        background-color: hsla(0, 0%, 0%, .15);
        backdrop-filter: blur(5px);
    }

    .container:hover .content {
        opacity: 1; /* Affiche le contenu au survol */
        transform: translate(-50%, -50%) translateY(0px);
    }

    .container:hover .permanent {
        transform: translate(-50%, -50%) translateY(-20px);
        color: white;
        background-color: hsla(0, 0%, 0%, .5);
    }

    .container .permanent {
        color: black;
        position: absolute;
        bottom: 0;
        left: 50%;
        transition: 1s ease-out; /* Transition pour l'effet de survol */
        transform: translate(-50%, -50%) translateY(0%);
        background-color: hsla(0, 0%, 0%, 0);
        border-radius: 15px;
        padding: 5px;
    }
</style>

<div class="container">
    <div class="content">
        <h1>Nom de l'entreprise</h1>
        <p>Description de l'entreprise</p>
        <p>Moyen de contacter</p>
    </div>
    <div class="permanent">Alternance développeur java</div>
</div>